# Generated by Django 3.2.4 on 2021-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
