# Generated by Django 3.2.4 on 2021-07-25 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('media', models.FileField(blank=True, upload_to=lib.functions.rename_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mkv', 'mp4', 'flv'])])),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('caption', models.TextField(blank=True, max_length=300, verbose_name='Caption')),
                ('allow_share', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='location.location')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
