# Generated by Django 3.2.4 on 2021-07-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
