# Generated by Django 3.2.4 on 2021-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user', '0002_alter_business_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ManyToManyField(related_name='business', to='location.Location'),
        ),
    ]
